-- VOZIA VAULT V8 - Supabase schema base
create table if not exists users (id bigserial primary key, vault_id text unique, name text not null, email text unique not null, password_hash text, photo_path text, plan text default 'avaliacao', accepted_terms boolean default false, accepted_terms_at timestamptz, guardian_name text default '', guardian_email text default '', guardian_phone text default '', guardian_relation text default '', subscription_status text default 'ativo', plan_expires_at date, plan_price numeric default 0, internal_note text default '', created_at timestamptz default now());
create table if not exists recordings (id bigserial primary key, user_id bigint references users(id) on delete cascade, phrase_index int not null, phrase_text text not null, category text default '', file_path text not null, duration_ms int default 0, quality_note text default '', created_at timestamptz default now(), unique(user_id, phrase_index));
create table if not exists legacy_messages (id bigserial primary key, user_id bigint references users(id) on delete cascade, title text not null, text_note text default '', file_path text not null, duration_ms int default 0, created_at timestamptz default now());
create table if not exists backup_requests (id bigserial primary key, user_id bigint references users(id) on delete cascade, requester_name text not null, requester_relation text not null, requester_document text default '', status text default 'pendente', decision_note text default '', decided_at timestamptz, created_at timestamptz default now());
create table if not exists deletion_requests (id bigserial primary key, user_id bigint references users(id) on delete cascade, reason text default '', status text default 'pendente', decision_note text default '', decided_at timestamptz, created_at timestamptz default now());
create table if not exists payment_events (id bigserial primary key, user_id bigint references users(id) on delete cascade, plan text not null, amount numeric default 0, method text default 'simulado', status text default 'confirmado', created_at timestamptz default now());
create table if not exists audit_log (id bigserial primary key, user_id bigint references users(id) on delete set null, action text not null, detail text default '', created_at timestamptz default now());
create table if not exists system_settings (key text primary key, value text default '');
create table if not exists license (id int primary key default 1, license_key text default '', plan text default 'avaliacao', valid_until date, status text default 'inativo', created_at timestamptz default now());
